### ISSUE TITLE
Medium account is logged out.

### ISSUE THREAD

**Issue by NguyenHuuAnhVu** [und3fined/medium-unlocker#3]
The extension works well when unlocking articles for free reading
But it crashed, the account was logged out when I clicked save post or clicked the clapping icon.

**Comment by und3fined** [comment]
Account logged out is fixed. Please use latest version

I'll debug for Page crashed

**Comment by NguyenHuuAnhVu** [comment]
> Account logged out is fixed. Please use latest version
> 
> I'll debug for Page crashed

I used the latest version
I noticed that when I go to https://medium.com/analytics-vidhya/..., click save or click the clapping icon, the account will be logged out.

**Comment by und3fined** [comment]
I ship 0.1.8, add more patch for request to graphql
It's avaliable in Mozilla Addons store, MS and Chrome score waiting for review...

**Comment by NguyenHuuAnhVu** [comment]
I used version 0.1.8 by downloading the zip file and selecting Load Unpacked on the extension manager page at edge://extensions but still getting the same error

**Comment by und3fined** [comment]
> I used version 0.1.8 by downloading the zip file and selecting Load Unpacked on the extension manager page at edge://extensions but still getting the same error

Please wait for review in store

**Comment by und3fined** [comment]
@NguyenHuuAnhVu I see a bug with Chromium core

**Comment by und3fined** [comment]
@NguyenHuuAnhVu I fixed logout in 0.1.11, please try it

**Comment by NguyenHuuAnhVu** [comment]
This version has fixed the previous error
But I still see a small bug when clicking on the save article icon. Choose an article and try saving it!
If you fix this problem, your extension will be perfect!
Thanks!

**Comment by und3fined** [comment]
> This version has fixed the previous error But I still see a small bug when clicking on the save article icon. Choose an article and try saving it! If you fix this problem, your extension will be perfect! Thanks!

I don't known it crash, i'll research it later

**Comment by und3fined** [comment]
@NguyenHuuAnhVu hi, version v0.1.11 approved in MS Add-ons store, please use it replace for zip version
